### ISSUE TITLE
Text Extraction Does Not Traverse Grouped/Smart Object Layers

### ISSUE THREAD

**Issue by eethann** [kartsims/psd-cli#1]
We have a PSD with a lot of text that's buried inside groups / smart objects (I'm not exactly certain, as I'm not the one with Photoshop, part of my draw to psd-cli). When using text extraction only a small subset of the text is extracted, I suspect because of this.

I can provide more info as requested. Will loop in other folks working on the same project who have more info.

**Comment by kartsims** [comment]
Would you have a link to a PSD file I could download to run some tests ?

**Comment by kartsims** [comment]
I would be glad to re-open this issue if you provide me an example of PSD I can test
