### ISSUE TITLE
Can't get multiple files in a folder to convert

### ISSUE THREAD

**Issue by bocciaman** [kartsims/psd-cli#12]
I've tried converting multiple files in a folder at once from PSD to PNG. 

I've tried the following:

PSD -c /myfilepath

and

PSD /myfilepath -c

Neither worked, can you help?

**Comment by kartsims** [comment]
Have you tried:

```
psd /myfilepath/* -c
```

**Comment by bocciaman** [comment]
I got this command to work: "psd *.psd -c" but first, I had to CD into the directory where the PSDs are located. Is there a way to run the command on a set of PSDs in one directory but have the output files created in another directory?

**Comment by kartsims** [comment]
No this option doesn't exist. If you feel like contributing you are most welcome!

I'll close this issue now :)
