### ISSUE TITLE
Issues with psd-cli

### ISSUE THREAD

**Issue by williamortiz** [kartsims/psd-cli#2]
hello, i was using this a few weeks back and worked fine.

now i getting this error.

William-Ortiz-2:~ wortiz$ psd juice/users/wortiz/test.psd  -t

Processing juice/users/wortiz/test.psd ...

juice/users/wortiz/test.psd could not be opened with PSD library

am i doing something wrong?

Thanks

**Comment by kartsims** [comment]
Hi !

`psd-cli` is basically a wrapper for the [psd](https://www.npmjs.com/package/psd) lib... So if it can't open, `psd-cli` just can't extract the texts... This is just a limitation of this utility, so no you didn't do anything wrong, it just can't work out.

For more information, check out [the psd package](https://www.npmjs.com/package/psd)
