### ISSUE TITLE
Error while converting multiple PSD's to PNG

### ISSUE THREAD

**Issue by spinside** [kartsims/psd-cli#6]
psd *.psd -o

Processing A 700 resolutie.psd ...

<--- Last few GCs --->

   10513 ms: Mark-sweep 1172.5 (1222.5) -> 1172.1 (1223.5) MB, 541.4 / 0.0 ms [allocation failure] [GC in old space requested].
   11031 ms: Mark-sweep 1172.1 (1223.5) -> 1172.1 (1192.5) MB, 517.7 / 0.0 ms [last resort gc].
   11560 ms: Mark-sweep 1172.1 (1192.5) -> 1172.1 (1192.5) MB, 529.5 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x6015e83fa99 <JS Object>
    1: /* anonymous */ [/usr/local/lib/node_modules/psd-cli/node_modules/psd/lib/psd/image_formats/rle.coffee:41] [pc=0x35833538d9ed] (this=0x3681144cfbd9 <an Image with map 0x1e2dfd479bb1>)
    2: decodeRLEChannel [/usr/local/lib/node_modules/psd-cli/node_modules/psd/lib/psd/image_formats/rle.coffee:~28] [pc=0x35833538e0c0] (this=0x3681144cfbd9 <an Image with map 0x1e2dfd479bb1>)
    3: parseCh...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/usr/local/bin/node]
 5: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedSmiElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)0> >::Splice(v8::internal::Handle<v8::internal::JSArray>, unsigned int, unsigned int, v8::internal::Arguments*, unsigned int) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_ArraySplice(v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)0>, v8::internal::Isolate*) [/usr/local/bin/node]
 7: v8::internal::Builtin_ArraySplice(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 8: 0x358334e060c7
Abort trap: 6

**Comment by kartsims** [comment]
not enough information, please provide files to reproduce this example
